#!/bin/bash


deployed_to=~/whm/AppData/Roaming/talon/user/

[[ -n $@ ]] && rule_file_pattern="$@" || rule_file_pattern="*.talon"

cp $(dirname $0)/$rule_file_pattern $deployed_to
echo "deployed to ${deployed_to}:"
ls -ltr $deployed_to | grep -v ".pyc$"
